version: 2.1

orbs:
  snyk: snyk/snyk@1.4.0
  android: circleci/android@2.1.2

jobs:

  security-scan:
    docker:
      - image: cimg/openjdk:19.0.1
    steps:
      - checkout
      - snyk/scan

  quality-check:
    docker:
      - image: cimg/android:2022.12
    steps:
      - checkout
      - run:
          name: Run Detekt
          command: ./gradlew detekt

  android-instrumentation-tests:
    executor:
      name: android/android-machine
      tag: 2022.12.1
      resource-class: large
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86

  android-unit-tests:
    docker:
      - image: cimg/android:2022.12
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./gradlew test

workflows:
  testing:
    jobs:
      - security-scan
      - android-instrumentation-tests
      - android-unit-tests
